FROM ubuntu:20.04

#Se instala ansible y sshpass
RUN apt-get update && apt-get install -y ansible sshpass

#Se habilita archivo inventario
RUN sed -i 's|#inventory      = /etc/ansible/hosts|inventory=/etc/ansible/hosts|' /etc/ansible/ansible.cfg

#Se agrega ip ubuntu ssh a hosts ansible
RUN echo '172.17.0.2' >>/etc/ansible/hosts

#Se genera llave ssh y se copia a contenedor ubuntu
RUN ssh-keygen -q -t rsa -N 'llave' -f /root/.ssh/id_rsa
RUN sshpass -p prueba ssh-copy-id -o "StrictHostKeyChecking no" root@172.17.0.2

#Se copia playbook desde local hacia contenedor ansible
COPY playdesa2.yml /root/playdesa2.yml
CMD ["/bin/bash"]
